# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: My Investment Journey
description: >- # this means to ignore newlines until "baseurl:"
  My personal investment journey
baseurl: "" # the subpath of your site, e.g. /blog
url: "dedsecinv.github.io" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# Contact links
twitter_username: PrasanthKanna27
github_username:  Kanna727
email: chitturiprasanth13797@gmail.com

#-------------------------------
# Comment Section (Disqus)
disqus-identifier: dedsecinv # Add your shortname for Disqus Comment. For example mr-brown

# Build settings
# theme: minima
# theme: jekyll-theme-hacker
markdown: kramdown
permalink: ':title/'
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

paginate: 7
paginate_path: "/page/:num"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

# Syntax highlighting
highlighter:         rouge

# Google Analytics
google-analytics: 258174923

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
